// tools/build-waves.mjs
// Build src/data/waveLibraryDetails.ts from public/data/waves.csv (rich sections)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Papa from "papaparse";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CSV_PATH = path.resolve(__dirname, "../public/data/waves.csv");
// ⬇️ write to a NEW file so we don't touch your sidebar data file
const OUT_PATH = path.resolve(__dirname, "../src/data/waveLibraryDetails.ts");

// Required columns (match your current header with 19 columns)
const REQD = [
  "id",
  "title",
  "summary",
  "anchors",
  "keywords",
  "harmonic_function",
  "core_essence",
  "geometric_analogy",
  "numerological_core",
  "anchors_desc",
  "archetypal_role",
  "lived_rel",
  "lived_evolution",
  "lived_service",
  "inner_alchemy",
  "psychological_tone",
  "wisdom_questions",
  "extra1_title",
  "extra1_text",
];

const FIELDS = {
  anchors_desc: "Anchors",
  harmonic_function: "Harmonic Function",
  core_essence: "Core Essence",
  geometric_analogy: "Geometric Analogy",
  numerological_core: "Numerological Core",
  archetypal_role: "Archetypal Role",
  lived_rel: "Lived Expressions — Relationships",
  lived_evolution: "Lived Expressions — Personal Evolution",
  lived_service: "Lived Expressions — Service/Vocation",
  inner_alchemy: "Inner Alchemy Themes",
  psychological_tone: "Psychological Tone",
  wisdom_questions: "Wisdom Questions",
};

function die(msg) {
  console.error("ERROR:", msg);
  process.exit(1);
}

function readCsv(fp) {
  if (!fs.existsSync(fp)) die(`File not found: ${fp}`);
  const raw = fs.readFileSync(fp, "utf8").replace(/^\uFEFF/, "");
  const parsed = Papa.parse(raw, { header: true, skipEmptyLines: "greedy" });
  if (parsed.errors?.length) {
    console.error(parsed.errors);
    die("CSV parse errors encountered.");
  }
  return parsed.data.map((r) =>
    Object.fromEntries(
      Object.entries(r).map(([k, v]) => [k.trim(), String(v ?? "").trim()])
    )
  );
}

function parseAnchors(s) {
  return (s || "")
    .split(/[,\|\s;]+/)
    .map(Number)
    .filter((n) => Number.isFinite(n));
}
function parseKeywords(s) {
  return (s || "")
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);
}
function normalizeNL(s) {
  return (s || "").replace(/\r\n/g, "\n");
}

// convert a cell into bullet list OR paragraphs
function blockize(text) {
  const t = normalizeNL(text);
  if (!t) return { paragraphs: [], bullets: [] };
  const lines = t
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
  const isBullet = lines.length >= 1 && lines.every((l) => /^[-•]\s+/.test(l));
  if (isBullet)
    return {
      paragraphs: [],
      bullets: lines.map((l) => l.replace(/^[-•]\s+/, "").trim()),
    };
  const paras = t
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean);
  return { paragraphs: paras, bullets: [] };
}

function validate(rows) {
  const header = new Set(Object.keys(rows[0] || {}));
  const missing = REQD.filter((h) => !header.has(h));
  if (missing.length) die(`Missing header column(s): ${missing.join(", ")}`);

  const ids = new Set();
  for (const r of rows) {
    const id = Number(r.id);
    if (!Number.isInteger(id) || id < 1 || id > 10)
      die(`Invalid id '${r.id}'. Must be 1..10.`);
    if (ids.has(id)) die(`Duplicate id: ${id}`);
    ids.add(id);
    for (const c of REQD) {
      if (typeof r[c] === "undefined") die(`Row id=${id} missing column: ${c}`);
    }
  }
  if (ids.size < 1) die("CSV has no valid rows.");
}

function generateTs(rows) {
  const waves = rows.map((r) => {
    const id = Number(r.id);
    const title = r.title;
    const summary = normalizeNL(r.summary);
    const anchors = parseAnchors(r.anchors);
    const keywords = parseKeywords(r.keywords);

    const sections = [];
    for (const [col, titleLabel] of Object.entries(FIELDS)) {
      const raw = r[col];
      if (!raw) continue;
      const { paragraphs, bullets } = blockize(raw);
      sections.push({
        id: col,
        title: titleLabel,
        ...(paragraphs.length ? { paragraphs } : {}),
        ...(bullets.length ? { bullets } : {}),
      });
    }

    // optional extra section pair
    if (r.extra1_title && r.extra1_text) {
      const { paragraphs, bullets } = blockize(r.extra1_text);
      sections.push({
        id: "extra1",
        title: r.extra1_title,
        ...(paragraphs.length ? { paragraphs } : {}),
        ...(bullets.length ? { bullets } : {}),
      });
    }

    return {
      id,
      shortId: id,
      title,
      summary,
      anchors,
      ...(keywords.length ? { keywords } : {}),
      sections,
    };
  });

  waves.sort((a, b) => a.id - b.id);

  const ts = `// AUTO-GENERATED by tools/build-waves.mjs — DO NOT EDIT BY HAND
// Source: public/data/waves.csv
// Regenerate: npm run build:waves

export type WaveLibId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export type WaveLibSection = {
  id: string;
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type WaveLibDetails = {
  id: WaveLibId;
  shortId: number;
  title: string;
  summary: string;
  anchors: number[];
  keywords?: string[];
  sections: WaveLibSection[];
};

export const waveLibDetailsById: Record<WaveLibId, WaveLibDetails> = ${JSON.stringify(
    Object.fromEntries(waves.map((w) => [w.id, w])),
    null,
    2
  ).replace(/"(\d+)":/g, "$1:")};
`;

  return ts;
}

function main() {
  const rows = readCsv(CSV_PATH);
  validate(rows);
  const ts = generateTs(rows);
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, ts, "utf8");
  console.log(`OK: wrote ${path.relative(process.cwd(), OUT_PATH)}`);
}

main();
